### ISSUE TITLE
thumb service: Provide a project installation rake task

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/was-thumbnail-service#4]
After running bundle install... Tried to run the tests 

``` sh
bundle exec rake
```

But had 12 failures due to MySQL installation failure. Can the MySQL dependencies be explicitly called out? Or added to the default rake task?

Also after running a

``` sh
bundle exec rake db:create RAILS_ENV=test
bundle exec rake db:migrate RAILS_ENV=test
```

I'm still getting a failure at:
rspec ./spec/was/thumbnail_service/capture/capture_thumbnail_spec.rb:42 # Was::ThumbnailService::Capture::CaptureThumbnail.capture should create an jpeg tempo

**Comment by aalsum** [comment]
Hi @mejackreed Do you have any example of a similar task in other projects?

**Comment by ndushay** [comment]
I am closing this.  Two reasons:

1.  We've got a build that works in travis (using mysql)o
2.  I have added a rake task to run all specs that pass with sqlite.  This will be in a PR that merges in `monitoring` branch (in progress).

I would prefer to use sqlite for testing, but that involves changing fixtures (simhash field has a value that seems to be computed specific to mysql), and since we are using mysql in production, perhaps it's just as well for the tests to run with mysql.
